### PR TITLE
add support for GNOME console and newer GNOME editors

### LINKED ISSUE #699: Support Gnome console as a terminal
### The feature request

currently, github desktop only supports the gnome terminal and not gnome console, it would be nice if it supported both. 

### Proposed solution

add an option to use gnome console as the terminal.

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
support gnome console as a terminal

Closes #699

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
so far detected in the options menu, but can't use it
edit: had to install konsole, switch it to konsole, then switch to gnome console and it worked fine, then uninstall konsole obviously
image

**Comment by shiftkey** [comment]
> edit: had to install konsole, switch it to konsole, then switch to gnome console and it worked fine, then uninstall konsole obviously

I believe this is related to https://github.com/shiftkey/desktop/issues/344

**Comment by Etaash-mathamsetty** [comment]
> > edit: had to install konsole, switch it to konsole, then switch to gnome console and it worked fine, then uninstall konsole obviously
> 
> I believe this is related to #344

also could you merge this btw

**Comment by Etaash-mathamsetty** [comment]
to solve #344, this could work right?
```
//have to enable top level awaits
async function getDefaultShell(): Promise<Shell> {
  const shells = await getAvailableShells()
  if (shells.length > 0) {
    return shells[0].shell
  }
  return Shell.Gnome
}

export const Default = await getDefaultShell()
```
pardon me if the code is bad, I code in c++ lol
need to figure out how to enable top level awaits, since no other way I tried works
edit: I have no idea how to enable it

**Comment by shiftkey** [comment]
> to solve #344, this could work right?

@Etaash-mathamsetty not sure, I'm very hazy on the issue and can't recall exactly what the root cause was. Let's kick that one down the road for now...

**Comment by shiftkey** [comment]
Thanks for the contribution @Etaash-mathamsetty!

**Pull request merged**
