### PR TITLE
add support for generating release notes from upstream release

### PR DESCRIPTION
**Pull request by shiftkey**
This PR adds support to the `script/generate-release-notes` tool to read the `changelog.json` entries where a version represents the first release based on the given upstream release, and generates the release body matching the template that we use currently, with a couple of tweaks:

 - `Fixes` and `Improvements` now get their own sections
 - SHA256 checksums section format changed (to support organizing by architecture)

### CODE REVIEW

**Comment by shiftkey** [comment]
Here's an example of the generated draft release body, using a previous release:

```
## Fixed

- Entering in double forward slash does not trim the target directory in the cloning dialog - https://github.com/desktop/desktop/issues/15842. Thanks @IgnazioGul!
- In the "No Repositories" screen, controls at the bottom stay inside window when it is resized - https://github.com/desktop/desktop/issues/16502. Thanks @samuelko123!
- Link to editor settings on the tutorial screen - https://github.com/desktop/desktop/issues/16636. Thanks @IgnazioGul!
- Fix crash using Edit -> Copy menu when no text is selected in the diff - https://github.com/desktop/desktop/issues/16876

## Improved

- Improve screen reader support of the "Create Alias" dialog - https://github.com/desktop/desktop/issues/16802
- Screen readers announce the number of results in filtered lists (like repositories, branches or pull requests) - https://github.com/desktop/desktop/issues/16779
- Screen readers announce expanded/collapsed state of dropdowns - https://github.com/desktop/desktop/issues/16781
- The context menu for a branches list items can be invoked by keyboard shortcuts - https://github.com/desktop/desktop/issues/16760
- The context menu for a repository list item can be invoked by keyboard shortcuts - https://github.com/desktop/desktop/issues/16758
- Make floating elements more responsive as the window or the UI are resized - https://github.com/desktop/desktop/issues/16717
- Adds committing avatar popover to see git configuration and ability to open git configuration settings - https://github.com/desktop/desktop/issues/16640
- Password inputs have a visibility toggle. - https://github.com/desktop/desktop/issues/16714
- Welcome flow screen change in context is announced - https://github.com/desktop/desktop/issues/16698
- Focus the sign in with browser button on opening the enterprise server login screen - https://github.com/desktop/desktop/issues/16706
- Show the remote branch name if it does not match the local branch name - https://github.com/desktop/desktop/issues/13591. Thanks @samuelko123!
- Reduce retries of avatars that fail to load - https://github.com/desktop/desktop/issues/16592
  
## SHA-256 checksums

## x64

**GitHubDesktop-linux-amd64-3.2.5-linux1.deb**
15cbb28356054f00edcf06f885e32777194faae9502f9f7520ad1cea62a3755c

**GitHubDesktop-linux-x86_64-3.2.5-linux1.AppImage**
2e453c9142f880f66435917c6ae5aeee825d2ee3bf993b7950ceeeb04a28d43c

**GitHubDesktop-linux-x86_64-3.2.5-linux1.rpm**
fe98f1ed3a46ca160df0b56fb3f49dd20745368a59f9dff22daf703f022361b6
```

**Comment by theofficialgman** [comment]
@shiftkey maybe it would be a good idea to make the release notes asset filenames links to the assets. since we can control the order the release notes are written in but the assets always appear in file alphabetical order

basically this
```
x64
6031515cb44652e573cd231aa2ae151768947f5612cbb98322c3dd2b9ed861d1 [GitHubDesktop-linux-amd64-3.2.7-test7.deb](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-amd64-3.2.7-test7.deb)
cdcb3e2299571488a33e87428ec7d800590fcb411a7577e687976bebbda1fdfc [GitHubDesktop-linux-x86_64-3.2.7-test7.AppImage](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-x86_64-3.2.7-test7.AppImage)
d15c1ab26d9be4725f646f39cd05513ae83643a9f8eca6d70d721f4ec4a1e828 [GitHubDesktop-linux-x86_64-3.2.7-test7.rpm](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-x86_64-3.2.7-test7.rpm)

ARM64
f1f3e4ca6a6c431dd0f80eaa10e35c5b1127847857d517abd605c69798f35198 [GitHubDesktop-linux-aarch64-3.2.7-test7.rpm](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-aarch64-3.2.7-test7.rpm)
ba96bfc5087af6500352b4069091e86fd683e9e74ef1cb8ff15e32ea483f5711 [GitHubDesktop-linux-arm64-3.2.7-test7.AppImage](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-arm64-3.2.7-test7.AppImage)
87b0f9276f903d49bdbbd4b410d797f0c40124cd23c2300a213960741857b750 [GitHubDesktop-linux-arm64-3.2.7-test7.deb](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-arm64-3.2.7-test7.deb)

ARM
34aba140ece5fe97ffe505d3f30c8989a3b3fc665969016df8bf93c56855bb2a [GitHubDesktop-linux-armhf-3.2.7-test7.deb](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-armhf-3.2.7-test7.deb)
428ca152623c3ad73f3738380d188d7118a9406e15c09b8d0a035a64a0abb054 [GitHubDesktop-linux-armv7l-3.2.7-test7.AppImage](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-armv7l-3.2.7-test7.AppImage)
ff0a2be3415bef33ed6e06f8356376478766115196b67745deeda2c692ea2785 [GitHubDesktop-linux-armv7l-3.2.7-test7.rpm](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-armv7l-3.2.7-test7.rpm)
```

x64
6031515cb44652e573cd231aa2ae151768947f5612cbb98322c3dd2b9ed861d1 [GitHubDesktop-linux-amd64-3.2.7-test7.deb](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-amd64-3.2.7-test7.deb)
cdcb3e2299571488a33e87428ec7d800590fcb411a7577e687976bebbda1fdfc [GitHubDesktop-linux-x86_64-3.2.7-test7.AppImage](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-x86_64-3.2.7-test7.AppImage)
d15c1ab26d9be4725f646f39cd05513ae83643a9f8eca6d70d721f4ec4a1e828 [GitHubDesktop-linux-x86_64-3.2.7-test7.rpm](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-x86_64-3.2.7-test7.rpm)

ARM64
f1f3e4ca6a6c431dd0f80eaa10e35c5b1127847857d517abd605c69798f35198 [GitHubDesktop-linux-aarch64-3.2.7-test7.rpm](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-aarch64-3.2.7-test7.rpm)
ba96bfc5087af6500352b4069091e86fd683e9e74ef1cb8ff15e32ea483f5711 [GitHubDesktop-linux-arm64-3.2.7-test7.AppImage](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-arm64-3.2.7-test7.AppImage)
87b0f9276f903d49bdbbd4b410d797f0c40124cd23c2300a213960741857b750 [GitHubDesktop-linux-arm64-3.2.7-test7.deb](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-arm64-3.2.7-test7.deb)

ARM
34aba140ece5fe97ffe505d3f30c8989a3b3fc665969016df8bf93c56855bb2a [GitHubDesktop-linux-armhf-3.2.7-test7.deb](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-armhf-3.2.7-test7.deb)
428ca152623c3ad73f3738380d188d7118a9406e15c09b8d0a035a64a0abb054 [GitHubDesktop-linux-armv7l-3.2.7-test7.AppImage](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-armv7l-3.2.7-test7.AppImage)
ff0a2be3415bef33ed6e06f8356376478766115196b67745deeda2c692ea2785 [GitHubDesktop-linux-armv7l-3.2.7-test7.rpm](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-test7/GitHubDesktop-linux-armv7l-3.2.7-test7.rpm)

**Comment by theofficialgman** [comment]
also since your script is also alphabetizing each individual release, maybe it would also be better to make the order standard. ie: deb then AppImage then rpm for each architecture.

**Comment by shiftkey** [comment]
@theofficialgman adding this to https://github.com/shiftkey/desktop/issues/901 ? I'm open to adapting the format to whatever makes sense here, just trying to juggle feedback from different angles...

**Pull request merged**
