### PR TITLE
Add Zed support for Linux external editor options

### PR DESCRIPTION
**Pull request by MVDW-Java**
Does not address any open issues

## Description

- Add Zed support for Linux external editor options

## Release notes

Notes:

### CODE REVIEW

**Review by aminya — APPROVED** [review]

**Review by shiftkey — APPROVED** [review]

**Comment by adil192** [comment]
I've made a PR upstream here: https://github.com/desktop/desktop/pull/18962

**Comment by shiftkey** [comment]
@adil192 I generally upstream the editors to the main project after a couple of releases, e.g. https://github.com/desktop/desktop/pull/18745 - but contributors are fine to do that directly

**Comment by adil192** [comment]
> @adil192 I generally upstream the editors to the main project after a couple of releases, e.g. [desktop#18745](https://github.com/desktop/desktop/pull/18745) - but contributors are fine to do that directly

Ah maybe I should reopen my PR targeting this repo instead? My PR has a lot more paths for various OS packages

**Comment by shiftkey** [comment]
@adil192 up to you, but I could merge your PR and push out an update later this week of this change on top of the latest release. The upstream project has their own release schedule, and I generally wait for them to tag a release to use as a starting point for releases from this repository...

**Pull request merged**
