### PR TITLE
Add support for detecting PhpStorm editor

### LINKED ISSUE #716: PhpStorm Jetbrains is not visible
### The problem

In options > integrations > external editor it should show PhpStorm, but it doesn't. All it shows is VSC, VSC (insiders), GNOME text editor.

### Release version

Version 2.9.3-linux3 (x64)

### Operating system

Ubuntu 20.04.3 LTS

### Steps to reproduce the behavior

_No response_

### Log files

_No response_

### Screenshots

https://cdn.padow.ru/c4mm

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PadowYT2**
Closes #716 

## Description

This only adds for snap, if you install it without snap (with an archive), it can be anywhere so yea.

### CODE REVIEW

**Review by shiftkey — APPROVED** [review]
Thanks for the contribution @PadowYT2!

**Comment by PadowYT2** [comment]
Hey @shiftkey, as I need the pr to be in a release, is there a way I can build the package myself right now? If yes, how so?

**Comment by shiftkey** [comment]
To generate a local release you can try this:

```
yarn 
yarn build:prod
yarn run package
```

**Comment by AlejandroAkbal** [comment]
Thank you PadowYT2 <3

**Pull request merged**
