### PR TITLE
duplicate workflow to test new approach in isolation

### PR DESCRIPTION
**Pull request by shiftkey**
Trying to unblock the node20 dependency updates while packaging with an earlier version of glibc, by shifting the packaging steps into a containerized actions.

The three repositories that will now handle this setup:

  - https://github.com/shiftkey/desktop-ubuntu-amd64-packaging
  - https://github.com/shiftkey/desktop-ubuntu-arm64-packaging
  - https://github.com/shiftkey/desktop-ubuntu-arm-packaging

### CODE REVIEW

**Comment by theofficialgman** [comment]
> Trying to unblock the node20 dependency updates while packaging with an earlier version of glibc

What is blocked? nodejs/unofficial-builds builds `linux-x64-glibc-217` for node20 as well.

**Comment by shiftkey** [comment]
> What is blocked? nodejs/unofficial-builds builds `linux-x64-glibc-217` for node20 as well.

I don't think I can swap in an a different flavour of node for these default Actions workflows"

```
Run actions/checkout@v4
/usr/bin/docker exec  0bbfc4e0c8493d6d277edd3a48d3581890b5fb4805a22dd1811cd36194d7f3b5 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

As I understand this error, I think this points to a path in it's own container and installing something before isn't going to change this setup.

**Comment by theofficialgman** [comment]
What script/action are you running above? Can you post a link to the action log?

**Comment by shiftkey** [comment]
This is from https://github.com/shiftkey/desktop/actions/runs/9276025558/job/25522092914?pr=929#step:7:31 where we're upgrading `action/checkout`.

**Comment by theofficialgman** [comment]
right... in theory you could supply an equivalent node version (from `nodejs/unofficial-builds`) for those github actions and remove `/__e/node20` as another option.

**Comment by shiftkey** [comment]
> right... in theory you could supply an equivalent node version (from `nodejs/unofficial-builds`) for those github actions and remove `/__e/node20` as another option.

I've not seen this done before - what am I missing?

**Pull request merged**
